version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 12.18.2
      - run: yarn install
      - run: yarn test

workflows:
    build-and-test:
      jobs:
        - build-and-test
